dist: trusty
sudo: false
addons:
  sauce_connect: true
language: node_js
node_js: node
script:
- yarn lint
- yarn test -- --plugin sauce --skip-plugin local
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/bower
env:
  global:
  - secure: ZZGV/B6TSetgb8wqkBM0xqBP9XAzMAtdSbrddPnmBgngvO6UjryX1qOQBFf1/AVkTbLY3KCLcrCaGzpvudAl8pshZMhJ5k5S4aI2VWpWC8bGy34eHVEgbKIkRoorQ1zGz4Pnkd2zqH1CbZ+b2fJ3tw4h0wwPqtdHAD9u6ABYIicK4fABs/CLc9TSgBD9+0mb20vp7yhLDnHGWXJWCXNi96krVsrywfo+2Pq32kx/PjNdvAfj/uSfaRWJdFJfRdP8rkoglpD5M1ItWmlMMrJkB7z3nVD3rdaJWcYjjankccwZsuP1atg0KiV8D2i2vAszyyWhtnP5dOBUZs3Ofc4mkUHHiO4XuLr5+K/sppO96hho09jIV0tDoPG5DH2kYQZc3UmO4CKeuQvo9Q1dZv0kTXcs2Oki6UPwv0uOeUwNuqBIkL7gFHwJ95zbUh2RQXD2VAxTFw8igucY/qia0x15N0pYQProCKQf2EvURvRIFCin5Et7rEdHPF9AmMKULd3MXoRyUj3PBfwzZD74hhSv3FWYUE28upBUp2mi0EppZ6frIQhceyh3HZYvi13Ln52YTFUcwVdVx61N7McRdB5A5NVyWNwiiJYnMDJ3dMwBhwVxArt6Ms/OiSuooY5dCSZyA6aI2V5+HUtgZ7Ae5cB/8S8pJiOFlUdMJE3WpJVRsKg=
  - secure: uEk1JldrWKOR0XwuGbZxzdoX7+Jr1ajgArhBCS2VUnU465i6sqXzXdYQr6xqJR+ou/UTIJB3I2agPOIe3UUcG76p2HGtkkNmjIeM8K9W+yV9UnLL1vsvnIAoeb3HjRJ3Gzr2i68zrrh5lT7G7w3CDL1N96WBD7bwFwjLq54IuWRipTB+ktvY4UwEd4zsL6U6PwtE4dXbN78qKkLLJ2sTYFnA+BQXFo//EOvkltMFEQdMXLfPs6+qG1Lxawhb4KrqmmQYR2ox0WJVVIaUHCCYYCICVdAykeYHDbiResUlggcIseJp65/QkUDVLC8Se/oP0PExASX2bRCoDC2WuTZ2mSbUJRSYhYoZscLZRnClzzw87GyfudVRr7UB3ayPqVUAEOiQWF2+QLpNXSfWlVze5veeD2rAYWUGYnODPJ0JwMExrf/NKc/FQMdzJfmKykt9+B3sVbRTXymNqD6lgURpD3anrVz2EYenLuvarlG5WQZ+zvM6r1RJhf4j13RLeRo6lMY5rRDS510M7FVlJ/l8KanD7RZYFboQLRNlQjmSpTidL4zuwRheLWMk2VrT93dGsk4RglBHSCMTfqg8qt/vVv1v+v2Byrsfq1BZjiuVfhtMQ9dCA/kL1gggKZl0IrmPUZwktWNd6WdjcAPAoGmsHvy6rB1+owFE3E9MnOGtYhY=
