dist: trusty
sudo: false
addons:
  firefox: "latest-dev"
language: node_js
node_js: "9"
script:
- yarn build
- yarn lint
- yarn test
- yarn test:e2e
cache:
  yarn: true
  directories:
  - node_modules
  - $HOME/.cache/bower
